### ISSUE TITLE
Data directory is missing from template 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/project-template#9]
The data directory is missing from the template. This makes sense for repos as in most cases we will not want to store data on github. But it should be included in the template so that we can enforce a similar data directory structure across project.

```
├── data
│   ├── external       <- Data from third party sources.
│   ├── interim        <- Intermediate data that has been transformed.
│   ├── processed      <- The final, canonical data sets for modeling.
│   └── raw            <- The original, immutable data dump.
```

Is it possible to add it in 2 PRs? on that removes `/data` from the `.gitignore` and pushes the directory, then a second that puts it back in the `.gitignore`? This will give everyone the same structure and keep data files from being added to github. 

Let me know if anyone knows of a better way to solve this. Thanks!

**Comment by chauhankaranraj** [comment]
+1. I think it'll be useful to have the data directories in the template, coz then all notebooks/src can use the same path (without checking every time) when saving/reading data locally.

Instead of two PR's, would it be possible to add `.gitkeep` in each `data` directory and then tell git to ignore all content in these except for the `.gitkeep`s? Something like this in `.gitignore`:
```
/data/**
!/data/**/
!/data/**/.gitkeep
```
